version: '3.8'

volumes:
  db-mysql-store:
  db-sqlserver-store:

networks:
  network-app:
    driver: bridge

services:
  cakephp-app:
    container_name: cakephp-app
    build: .
    volumes:
      - ./cake-app:/var/www/html
      - ./apache-config:/etc/apache2/sites-available                                  # Gắn kết thư mục cấu hình
      - ./apache-config/apache-selfsigned.crt:/etc/ssl/certs/apache-selfsigned.crt    # Gắn kết chứng chỉ SSL
      - ./apache-config/apache-selfsigned.key:/etc/ssl/private/apache-selfsigned.key  # Gắn kết key SSL
    ports:
      - 3000:80
      - 3443:443  # Ánh xạ cổng HTTPS
    networks:
      - network-app

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cakephp-app
    ports:
      - 3306:3306
    volumes:
      - db-mysql-store:/var/lib/mysql
    networks:
      - network-app

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - db-sqlserver-store:/var/opt/mssql
    networks:
      - network-app